export const USER_LOG_IN_LOADING = "SET_LOG_IN_LOADING";
export const USER_LOG_IN_COMPLETED = "USER_LOG_IN_COMPLETED";
export const USER_LOG_IN_ERROR = "USER_LOG_IN_ERROR";

export const USER_LOG_OUT_LOADING = "USER_LOG_OUT_LOADING";
export const USER_LOG_OUT_COMPLETED = "USER_LOG_OUT_COMPLETED";
export const USER_LOG_OUT_ERROR = "USER_LOG_OUT_ERROR";

export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_COMPLETED = "USER_REGISTER_COMPLETED";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_EDIT_LOADING = "USER_EDIT_LOADING";
export const USER_EDIT_COMPLETED = "USER_EDIT_COMPLETED";
export const USER_EDIT_ERROR = "USER_EDIT_ERROR";

export const USER_DELETE_LOADING = "USER_DELETE_LOADING";
export const USER_DELETE_COMPLETED = "USER_DELETE_COMPLETED";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";

export const USER_CHANGE_PHOTO_LOADING = "USER_CHANGE_PHOTO_LOADING";
export const USER_CHANGE_PHOTO_COMPLETED = "USER_CHANGE_PHOTO_COMPLETED";
export const USER_CHANGE_PHOTO_ERROR = "USER_CHANGE_PHOTO_ERROR";
